Cambio de CFLAGS

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -48,11 +48,14 @@ OPTIONS=(
   "libtheora_static:yes"
   "libvorbis:yes"
   "libvorbis_static:yes"
-  "libfdkaac:yes"
+  "libfdkaac:no"
   "libfdkaac_static:yes"
-  "nvenc:auto"
-  "qsv:no"
-  "libmfx_static:yes"
+  "libopus:yes"
+  "libopus_static:yes"
+  "nvenc:no"
+  "vaapi:auto"
+  "mmal:no"
+  "omx:no"
   "inotify:auto"
   "epoll:auto"
   "pcre:auto"
@@ -72,6 +75,7 @@ OPTIONS=(
   "slow_memoryinfo:no"
   "libsystemd_daemon:no"
   "bintray_cache:yes"
+  "ddci:no"
 )
 
 #
@@ -271,6 +275,12 @@ int test(void)
   return 0;
 }
 ' -liconv
+
+if enabled libiconv; then
+  printf "    ^ using external iconv library\n"
+else
+  printf "    ^ using build-in glibc iconv routines\n"
+fi
 
 if enabled_or_auto dvben50221; then
   check_cc_snippet libdvben50221 '
@@ -522,36 +532,39 @@ if enabled ffmpeg_static; then
     disable libfdkaac_static
   fi
 
-  # nvenc
-  if enabled_or_auto nvenc; then
-    if check_cc_header nvEncodeAPI; then
-      enable nvenc
-    elif enabled nvenc; then
-      die "NVENC library (https://developer.nvidia.com/nvidia-video-codec-sdk) not found"
+  # libopus
+  if enabled libopus; then
+    if disabled libopus_static; then
+      check_pkg opus ">=1.1" || die "opus package not found"
     fi
-  fi
-
-  # qsv
-  if enabled qsv; then
-    if disabled libmfx_static; then
-      check_pkg libmfx ">=1.16" || die "libmfx package not found"
-    else
-      check_bin autoreconf       || die "autoreconf not found"
-      check_bin libtool          || die "libtool not found"
-      check_bin libtoolize       || die "libtoolize not found"
-      check_cc_lib stdc++ stdcpp || die "libstdc++ not found"
-    fi
-    enable vaapi
   else
-    disable libmfx_static
+    disable libopus_static
   fi
 
-  # vaapi
-  if enabled vaapi; then
-    check_pkg libva ">=0.38.0"     || \
-      die "vaapi (Video Acceleration (VA) API for Linux) not found"
-    check_pkg libva-x11 ">=0.38.0" || die "libva-x11 not found"
-    check_pkg libva-drm ">=0.38.0" || die "libva-drm not found"
+  # nvenc
+  # latest ffmpeg has own code
+  if enabled_or_auto nvenc; then
+    #check_cc_header nvEncodeAPI || \
+    #  die "NVENC library (https://developer.nvidia.com/nvidia-video-codec-sdk) not found"
+    enable nvenc
+  else
+    disable nvenc
+  fi
+
+  # omx
+  if enabled omx; then
+    OLDCFLAGS=$CFLAGS
+    if [ -d "/opt/vc/include" ]; then
+      CFLAGS="-I/opt/vc/include $CFLAGS"
+    fi
+    check_cc_header "bcm_host" omx_rpi
+    if enabled omx_rpi; then
+      CFLAGS="-I/opt/vc/include/IL $OLDCFLAGS"
+      enable mmal
+    else
+      CFLAGS=$OLDCFLAGS
+    fi
+    check_cc_header OMX_Core omx || die "OpenMAX IL not found"
   fi
 
 else
@@ -559,13 +572,13 @@ else
   if enabled_or_auto libav; then
     has_libav=true
 
-    check_pkg libavfilter   ">=6.31.100"  || has_libav=false
-    check_pkg libswresample ">=2.0.101"   || has_libav=false
+    check_pkg libavfilter   ">=6.47.100"  || has_libav=false
+    check_pkg libswresample ">=2.1.100"   || has_libav=false
     check_pkg libavresample ">=3.0.0"     || has_libav=false
-    check_pkg libswscale    ">=4.0.100"   || has_libav=false
-    check_pkg libavformat   ">=57.25.100" || has_libav=false
-    check_pkg libavcodec    ">=57.24.102" || has_libav=false
-    check_pkg libavutil     ">=55.17.103" || has_libav=false
+    check_pkg libswscale    ">=4.1.100"   || has_libav=false
+    check_pkg libavformat   ">=57.41.100" || has_libav=false
+    check_pkg libavcodec    ">=57.48.101" || has_libav=false
+    check_pkg libavutil     ">=55.28.100" || has_libav=false
 
     if $has_libav; then
       enable libav
@@ -579,6 +592,22 @@ else
 
   fi
 
+fi
+
+#
+# vaapi
+#
+if enabled_or_auto vaapi; then
+  if enabled libav; then
+    if check_pkg libva ">=0.38.0"; then
+      check_pkg libva-x11 ">=0.38.0" || die "libva-x11 not found"
+      check_pkg libva-drm ">=0.38.0" || die "libva-drm not found"
+      enable vaapi
+      enable hwaccels
+    elif enabled vaapi; then
+      die "vaapi (Video Acceleration (VA) API for Linux) not found"
+    fi
+  fi
 fi
 
 #
@@ -620,6 +649,13 @@ if enabled linuxdvb; then
   if enabled libdvben50221; then
     LDFLAGS="$LDFLAGS -ldvben50221 -ldvbapi -lucsi"
     enable linuxdvb_ca
+  fi
+fi
+
+# DD CI support
+if enabled ddci; then
+  if disabled linuxdvb_ca; then
+    die "DD CI requires linuxdvb_ca (linuxdvb libdvben50221) (use --disable-ddci)"
   fi
 fi
 
@@ -702,7 +738,7 @@ fi
 # systemd
 #
 if enabled_or_auto libsystemd_daemon; then
-  if check_pkg libsystemd-daemon; then
+  if check_pkg libsystemd-daemon || check_pkg libsystemd; then
     enable libsystemd_daemon
   elif enabled libsystemd_daemon; then
     die "libsystemd-daemon development support not found (use --disable-systemd_daemon)"
